config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server, :at => "/resque"

  get "/auth/:developer/callback", to: "users#create_with_twitter"
  post "/auth/:developer/callback", to: "users#create_with_twitter"
  get "/users/twitter_confirm", to: "users#confirm_with_twitter"
  put "/users/twitter_confirm", to: "users#finalize_twitter"

  get  "/events",          to: "events#index", as: :events
  get  "/events/new",      to: "events#new"
  post "/events",          to: "events#create"
  get  "/events/:id/show", to: "events#show", as: :show_event

  get    "/events/:id/edit",  to: "events#edit",    as: :event
  post   "/events/:id/edit",  to: "events#edit"

  put    "/events/:id",      to: "events#update"
  patch  "/events/:id/edit",      to: "events#update"

  get "/users/new",            to: "users#new", as: :users
  post "/users/new",           to: "users#create"

  get "/users/show",       to: "users#show", as: :user

  get    "/users/:id/edit",  to: "users#edit"
  post   "/users/:id/edit",  to: "users#edit"

  put    "/users/:id/",      to: "users#update"
  patch  "/users/show",      to: "users#update"

  get "/users/show", to: "users#request_admin_mail", as: :admin_req
  post "/users/show", to: "users#request_admin_mail"

  delete "/",         to: "home#destroy", as: :logout

  get "home/login",   to: "home#login", as: :login
  post "home/login",   to: "home#login"

  get "/tools",       to: "tools#index", as: :tools
  post "/tools/:id",   to: "tools#update", as: :tool

  get "/posts",       to: "posts#index", as: :posts
  get  "/posts/new",  to: "posts#new", as: :new_post
  get "/posts/:id/edit", to: "posts#edit", as: :edit_post
  get "/posts/:id",   to: "posts#show", as: :post
  put "/posts/:id",   to: "posts#update"
  delete "/posts/:id", to: "posts#destroy", as: :delete_post
  post "/posts",      to: "posts#create"

  root "home#index"

end

app/models/tool.rb
class Tool < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true
  validates :status, presence: true
  validates :status, format: { with: /in|out/, message: "must be in or out"}

  def set_user_id(current_user_id)
    if status == "out"
      update(user_id: current_user_id)
    elsif status == "in"
      update(user_id: nil)
    end
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @available_tools = Tool.order(status: :asc)
    @unavailable_tools = Tool.order(status: :desc)
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(status: params[:status])
      @tool.set_user_id(session[:user_id])
      redirect_to tools_path, notice: "#{@tool.name} successfully checked out!"
    else
      redirect_to tools_path, notice: "#{@tool.name} did not update with status"
    end
  end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/_show.html.erb
<div  class="panel panel-success" id="home">
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to "Tools", "/tools"  %></h3>
  </div>

  <table class="table table-hover">
    <% @tools.each do |tool| %>
      <tr>
        <td><%= tool.name %></td>
        <td><%= tool.status %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="2"><%= link_to "See all tools", tools_path %></td>
    </tr>
  </table>


</div>

app/views/tools/index.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-md-6">
      <div class = "tools-table">

        <h3>Currently available tools:</h3>
        <hr>
        <% if @available_tools.empty? %>
          <p>There are no tools available!</p>
        <% else %>

          <table class="table table-hover" id="available-tools-list">
            <tr>
              <th>Tool Name</th>
              <th>Status</th>
              <th>Check Out</th>
            </tr>
            <% @available_tools.each do |tool| %>
              <tr id = "<%= tool.id %>" class="tool <%= 'available' if tool.status == "in" %> <%= 'unavailable' if tool.status == "out" %>">
                <td class="tool-name"><%= tool.name %></td>
                <td class="tool-status"><%= tool.status %></td>
                <td>
                  <% if current_user != nil %>
                    <%= button_to "Check me out!", tool_path(tool.id), method: :post, class: "btn btn-primary check-out", params: {status: "out"} %>
                  <% else %>
                    Sign up for an account to reserve tools!
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        <% end %>
      </div>
    </div>

    <div class = "col-md-6">
      <div class = "tools-table">
        <h3>Unavailable tools:</h3>
        <hr>
        <% if @unavailable_tools.empty? %>
          <p>All the tools are checked in!</p>
        <% else %>
          <table class="table table-hover" id = "unavailable-tools-list">
            <tr>
              <th>Tool Name</th>
              <th>Status</th>
              <th>Checked out to:</th>
            </tr>
            <% @unavailable_tools.each do |tool| %>
              <tr id = "<%= tool.id %>"class="tool <%= 'unavailable' if tool.status == "out" %> <%= 'available' if tool.status == "in" %>">
                <td class="tool-name"><%= tool.name %></td>
                <td class="tool-status"><%= tool.status %></td>
                <td>
                  <% if current_user != nil && tool.user_id == current_user.id %>
                    <%= button_to "Return this tool!", tool_path(tool.id), method: :post, class: "btn btn-danger check-in", params: {status: "in"} %>
                  <% elsif tool.status == "in" %>
                    <%= button_to "Return this tool!", tool_path(tool.id), method: :post, class: "btn btn-danger check-in", params: {status: "in"} %>

                  <% else %>
                    <%= tool.user_id %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        <% end %>
      </div>
    </div>

  </div>
</div>