config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server, :at => "/resque"

  get "/auth/:developer/callback", to: "users#create_with_twitter"
  post "/auth/:developer/callback", to: "users#create_with_twitter"
  get "/users/twitter_confirm", to: "users#confirm_with_twitter"
  put "/users/twitter_confirm", to: "users#finalize_twitter"

  get  "/events",          to: "events#index", as: :events
  get  "/events/new",      to: "events#new"
  post "/events",          to: "events#create"
  get  "/events/:id/show", to: "events#show", as: :show_event

  get    "/events/:id/edit",  to: "events#edit",    as: :event
  post   "/events/:id/edit",  to: "events#edit"

  put    "/events/:id",      to: "events#update"
  patch  "/events/:id/edit",      to: "events#update"

  get "/users/new",            to: "users#new", as: :users
  post "/users/new",           to: "users#create"

  get "/users/show",       to: "users#show", as: :user

  get    "/users/:id/edit",  to: "users#edit"
  post   "/users/:id/edit",  to: "users#edit"

  put    "/users/:id/",      to: "users#update"
  patch  "/users/show",      to: "users#update"

  get "/users/show", to: "users#request_admin_mail", as: :admin_req
  post "/users/show", to: "users#request_admin_mail"

  delete "/",         to: "home#destroy", as: :logout

  get "home/login",   to: "home#login", as: :login
  post "home/login",   to: "home#login"

  get "/tools",       to: "tools#index", as: :tools
  post "/tools/:id",   to: "tools#update", as: :tool

  get "/posts",       to: "posts#index", as: :posts
  get  "/posts/new",  to: "posts#new", as: :new_post
  get "/posts/:id/edit", to: "posts#edit", as: :edit_post
  get "/posts/:id",   to: "posts#show", as: :post
  put "/posts/:id",   to: "posts#update"
  delete "/posts/:id", to: "posts#destroy", as: :delete_post
  post "/posts",      to: "posts#create"

  root "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password_signup
  attr_accessor :twitter_signup

  has_many :posts
  has_many :comments
  has_many :events
  has_many :tools

  has_secure_password validations: false
  validates :password, length: { minimum: 4 }, confirmation: true, if: :password_signup

  validates :email, presence: true, confirmation: true, if: :twitter_signup
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, confirmation: true,
    if: :password_signup,
    if: :twitter_signup

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)
    @user.password_signup = true
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path

    else
      render :new
    end
  end

  def create_with_twitter
    auth_hash = request.env['omniauth.auth']
    if User.find_by(uid: auth_hash.uid)
      @user = User.find_by(uid: auth_hash.uid)
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You are logged in!"
    else
      @user = User.new(name: auth_hash.info.name, uid: auth_hash.uid)
      if @user.save
        session[:user_id] = @user.id
        redirect_to "/users/twitter_confirm"
      else
        redirect_to root_path, notice: "Sorry, an error ocurred!"
      end
    end
  end

  def confirm_with_twitter
    @user = current_user
  end

  def finalize_twitter
    @user = current_user
    @user.twitter_signup = true
    if @user.update(params.require(:user).permit(:name, :email))
      redirect_to root_path, notice: "You have signed up with twitter!"
    else
      render :finalize_twitter
    end
  end

  def show
    @user = User.find(session[:user_id])
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    @user.password_signup = true
    if @user.update(user_params)
      redirect_to user_path(user_params), notice: "You have updated your information"
    else
      render :show
    end

  end

  def request_admin_mail
    @user = User.find(session[:user_id])
    user_id = @user.id

    Resque.enqueue(AdminEmailJob, user_id)
    redirect_to user_path



  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/confirm_with_twitter.html.erb
<h1>Complete your registration:</h1>

<%= bootstrap_form_for @user, url: "/users/twitter_confirm", method: :put do |f| %>
  <%= f.text_field :name, value: @user.name %>
  <%= f.text_field :email %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
<div  class="panel panel-success" id="user_account">
  <div class="panel-heading">
    <h3 class="panel-title">Edit Account Information </h3></div>

    <table class="table table-hover">
      <%= bootstrap_form_for(@user, label_errors: false, inline_errors: false) do |f|%>
      <tr>
        <td>
          <%= f.text_field :name, label: "Username", icon: "user" %>
        </td>
      </tr>

      <tr>
        <td>
          <%= f.text_field :email%><%= f.errors_on :email, hide_attribute_name: false %>
        </td>
      </tr>

      <tr>
        <td>
          <%= f.password_field :password, label: "New Password" %><%= f.errors_on :password, hide_attribute_name: false %>
        </td>
      </tr>

      <tr>
        <td>
          <%= f.password_field :password_confirmation %><%= f.errors_on :password_confirmation, hide_attribute_name: false %>
        </td>
      </tr>

      <tr>
        <td>
          <%= f.submit "Save Changes"%>
        </td>
      </tr>

      <% end %>

    </table>

  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row new-user-content">
    <div class = "col-sm-5">
      <div class="login">


      <%= bootstrap_form_for(@user, label_errors: false, inline_errors: false) do |f|%>

      <div><%= f.text_field :name, label: "Username", icon: "user" %></div>



      <div><%= f.text_field :email%><%= f.errors_on :email, hide_attribute_name: false %></div>


      <div><%= f.password_field :password %><%= f.errors_on :password, hide_attribute_name: false %></div>

      <div><%= f.password_field :password_confirmation %><%= f.errors_on :password_confirmation, hide_attribute_name: false %></div>

      <div><%= f.submit %></div>

      <% end %>
      </div>
    </div>


    <div class = "col-sm-2">
      <h2 style="text-align:center" class="or">OR</h2>
    </div>
    <div class = "col-sm-5">
      <div>
        <%= link_to "Sign Up with Twitter", "/auth/twitter" , class: "twitter-auth-button btn btn-primary btn-block" %>
      </div>



</div>

app/views/users/show.html.erb
<div class="row">
<div  class="panel panel-success" id="user_account">
  <div class="panel-heading">
    <h3 class="panel-title">Account Information</h3></div>

    <table class="table table-hover">

        <tr>
          <td>
          <%= @user.name%>
        </td>
        </tr>

        <tr>
          <td>
        <%= @user.email %>
      </td>
      </tr>

      <tr>
        <td>
        <%= button_to "Edit", "/users/#{@user.id}/edit", {class: 'btn btn-warning'} %>
      </td>
      </tr>

      <tr>
        <td>
        <%= button_to "Request Admin", admin_req_path, {class: 'btn btn-info'} %>   </td></tr>




      </td>


    </table>

  </div>


</div>