config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server, :at => "/resque"

  get "/auth/:developer/callback", to: "users#create_with_twitter"
  post "/auth/:developer/callback", to: "users#create_with_twitter"
  get "/users/twitter_confirm", to: "users#confirm_with_twitter"
  put "/users/twitter_confirm", to: "users#finalize_twitter"

  get  "/events",          to: "events#index", as: :events
  get  "/events/new",      to: "events#new"
  post "/events",          to: "events#create"
  get  "/events/:id/show", to: "events#show", as: :show_event

  get    "/events/:id/edit",  to: "events#edit",    as: :event
  post   "/events/:id/edit",  to: "events#edit"

  put    "/events/:id",      to: "events#update"
  patch  "/events/:id/edit",      to: "events#update"

  get "/users/new",            to: "users#new", as: :users
  post "/users/new",           to: "users#create"

  get "/users/show",       to: "users#show", as: :user

  get    "/users/:id/edit",  to: "users#edit"
  post   "/users/:id/edit",  to: "users#edit"

  put    "/users/:id/",      to: "users#update"
  patch  "/users/show",      to: "users#update"

  get "/users/show", to: "users#request_admin_mail", as: :admin_req
  post "/users/show", to: "users#request_admin_mail"

  delete "/",         to: "home#destroy", as: :logout

  get "home/login",   to: "home#login", as: :login
  post "home/login",   to: "home#login"

  get "/tools",       to: "tools#index", as: :tools
  post "/tools/:id",   to: "tools#update", as: :tool

  get "/posts",       to: "posts#index", as: :posts
  get  "/posts/new",  to: "posts#new", as: :new_post
  get "/posts/:id/edit", to: "posts#edit", as: :edit_post
  get "/posts/:id",   to: "posts#show", as: :post
  put "/posts/:id",   to: "posts#update"
  delete "/posts/:id", to: "posts#destroy", as: :delete_post
  post "/posts",      to: "posts#create"

  root "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    @posts = Post.order(created_at: :desc).limit(10)
    @tools = Tool.where(status: "in").limit(10)
    @events = Event.sort_by_date
  end



  def login

   @login_user = User.find_by(name: params[:user][:name])
      if  @login_user.authenticate(params[:user][:password])
        session[:user_id] = @login_user.id
        redirect_to root_path, :notice => "Welcome back, #{@login_user.email}"
      else
        redirect_to root_path,  :notice => "Invalid email or password"
      end
  end

  def log_out
    session.delete(:user_id)
    @user = nil
  end

  def destroy
    log_out
    redirect_to root_path
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_index_login.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to  image_tag("peas.png"), "/"  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">


        <div class= "login">
          <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: name %>
          <% end %>
        </div>

        <% if session[:user_id] != nil  %>
        <li>
          <%= button_to "My Account", user_path,
          class: "btn btn-success my-account" %>
        </li>
        <li>
          <%= button_to "Logout", logout_path,
          :method => :delete,
          class: "btn btn-danger logout" %>
        </li>


        <% else  %>
        <li>
          <%= bootstrap_form_for @login_user, url: login_path, class: "navbar-form navbar-right" do |f|%>
            <div class = "login_field">
              <%= f.text_field :name, placeholder: "Name", hide_label: true %>
            </div>

            <div class = "login_field">
              <%= f.password_field :password, placeholder: "Password", hide_label: true %>
            </div>

            <div class = "login_field" >
              <%= f.submit "Login" %>
            </div>

          <% end %>
        </li>

        <li>
          <div class = "login_field twitter-button">
            <p><%= link_to image_tag("twitter_signin.png"),
            "/auth/twitter"  %></p>
          </div>
        </li>

        <li>
          <div class ="new_account">
            <%= link_to "Create a new account",
            users_path,
            class: "btn btn-sm btn-primary" %>

          </div>


        </li>
        <% end %>

      </ul>

      <div>
    </div>

      <ul class="nav navbar-nav navbar-right">

        <li>

        </li>

      </ul>
      <!-- <ul class="nav navbar-nav navbar-right"> -->
        <!-- <li>
          <div class ="new_account">
            <%#= link_to "Create a new account",
            users_path,
            class: "btn btn-sm btn-primary" %>
          </div>
        </li> -->
      <!-- </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_weather.html.erb
<% if Resque.redis.get("temperature") == "unavailable" %>
  <p>Weather currently unavailable, sorry! </p>
<% else %>
  <div class="current-weather">
    <strong>Current weather for Seattle, WA</strong>:
    <div class = "weather-info">
      <%= weather.temp %>° |
      <%= image_tag weather.icon, class: "weather-icon" %> |
      <%= weather.description %>
      <span class="expand-forecast btn btn-sm btn-default">see forecast</span>
      <span class="close-forecast btn btn-sm btn-default">X</span>
    </div>
  </div>
  <div class= "forecast">
    <table class="table table-striped forecast-table">
      <tr>
        <th colspan="4">Forecast for Seattle, WA</th>
      </tr>
      <tr>
        <% weather.day_array.each do |day| %>
          <th>
            <%= day %>
          </th>
        <% end %>
      </tr>
      <tr>
        <% weather.icon_array.each do |icon| %>
          <td>
            <%= image_tag icon, class: "weather-icon" %>
          </td>
        <% end %>
      </tr>
      <tr>
        <% weather.condition_array.each do |condition| %>
          <td>
            <%= condition %>
          </td>
        <% end %>
      </tr>
    </table>
  </div>
<% end %>

app/views/home/index.html.erb
<br>

<div class="row home-page">
  <div class="col-sm-4 ">
    <!-- PARTIAL FOR NEWS -->
    <%= render "/posts/show" %>
  </div>


  <div class="col-sm-4">
    <!-- PARTIAL FOR TOOLS -->
    <%= render "/events/show" %>
  </div>

  <div class="col-sm-4 ">
    <%= render "/tools/show" %>
  </div>
</div>