config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount Resque::Server, :at => "/resque"

  get "/auth/:developer/callback", to: "users#create_with_twitter"
  post "/auth/:developer/callback", to: "users#create_with_twitter"
  get "/users/twitter_confirm", to: "users#confirm_with_twitter"
  put "/users/twitter_confirm", to: "users#finalize_twitter"

  get  "/events",          to: "events#index", as: :events
  get  "/events/new",      to: "events#new"
  post "/events",          to: "events#create"
  get  "/events/:id/show", to: "events#show", as: :show_event

  get    "/events/:id/edit",  to: "events#edit",    as: :event
  post   "/events/:id/edit",  to: "events#edit"

  put    "/events/:id",      to: "events#update"
  patch  "/events/:id/edit",      to: "events#update"

  get "/users/new",            to: "users#new", as: :users
  post "/users/new",           to: "users#create"

  get "/users/show",       to: "users#show", as: :user

  get    "/users/:id/edit",  to: "users#edit"
  post   "/users/:id/edit",  to: "users#edit"

  put    "/users/:id/",      to: "users#update"
  patch  "/users/show",      to: "users#update"

  get "/users/show", to: "users#request_admin_mail", as: :admin_req
  post "/users/show", to: "users#request_admin_mail"

  delete "/",         to: "home#destroy", as: :logout

  get "home/login",   to: "home#login", as: :login
  post "home/login",   to: "home#login"

  get "/tools",       to: "tools#index", as: :tools
  post "/tools/:id",   to: "tools#update", as: :tool

  get "/posts",       to: "posts#index", as: :posts
  get  "/posts/new",  to: "posts#new", as: :new_post
  get "/posts/:id/edit", to: "posts#edit", as: :edit_post
  get "/posts/:id",   to: "posts#show", as: :post
  put "/posts/:id",   to: "posts#update"
  delete "/posts/:id", to: "posts#destroy", as: :delete_post
  post "/posts",      to: "posts#create"

  root "home#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    post_id = @post.id
    if @post.save
      Resque.enqueue(EmailJob, post_id)
    end
    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id)

  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_show.html.erb
  <div  class="panel panel-success" id="home">
    <div class="panel-heading">
      <h3 class="panel-title"><%= link_to "News", "/posts"  %></h3>
    </div>

    <table class="table table-hover">
      <% @posts.each do |post| %>
        <tr>
          <td>
            <%= link_to post.title, post_path(post.id) %>
          </td>
          <td>
            <%= post.created_at.strftime("%B %d, %Y") %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2"><%= link_to "See More Posts", posts_path, class: "panel-link" %></td>
      </tr>
    </table>



  </div>

app/views/posts/edit.html.erb
<div class="container">

  <%= bootstrap_form_for @post, method: :put do |f| %>

    <%= f.text_field :title, label: "Title" %>
    <%= f.text_area :content, label: "Content" %>
    <%= f.submit %>

  <% end %>

</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="news-article">
    <div class="news-header">
      <h2>News!
        <span>
          <% if session[:user_id] != nil && current_user.status == "admin" %>
            <%= link_to "Add a post", new_post_path, class: "btn btn-primary" %>
          <% end %>
        </span>
      </h2>
    </div>
    <hr>
    <% @posts.each do |post| %>
      <div class = "post-list-item">
        <a href = "<%= post_path(post.id) %>">
          <h3><%= post.title.titleize %></h3>
          <%= post.created_at.strftime("%B %d, %Y") %>
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class= "container">
  <% if session[:user_id] != nil && current_user.status == "admin" %>

    <%= bootstrap_form_for @post, class: "new-post-form" do |f| %>
    <%= f.text_field :title %>
    <%= f.text_area :content %>
    <%= f.hidden_field :user_id, :value => current_user.id%>
    <%= f.submit %>
    <% end %>

  <% else %>

    <div></div>

  <% end %>
</div>

app/views/posts/show.html.erb
<div class = 'row'>
  <div class= "news-article">
    <h2><%= @post.title %></h2>
    <span class="date"><%= @post.created_at.strftime("%B %d, %Y") %></span>
    <hr>
    <p><%= @post.content %></p>
    <% if session[:user_id] != nil && current_user.status == "admin" %>
      <%= link_to "Edit this Article", edit_post_path(@post.id), class: "btn btn-info" %>
      <%= button_to "Delete this Article", delete_post_path(@post.id), method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>
  <br>

  <div id="disqus_thread"></div>
  <script type="text/javascript">
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'peapatch2'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

</div>